Issuecomment
wri/wri-odp pull request #178
Opened 2023-12-29 06:53 UTC by steveoni

This pr adds issue functionality to dataset page

<img width="859" alt="Screenshot 2023-12-29 at 07 51 49" src="https://github.com/wri/wri-odp/assets/20904032/3f14a0b8-4e6a-4e6e-8a2b-30570a06ac7d">
<img width="838" alt="Screenshot 2023-12-29 at 07 52 03" src="https://github.com/wri/wri-odp/assets/20904032/2439d083-ddd3-4b3c-a8be-7a3549955559">

2023-12-29 06:55 UTC, steveoni commented
@luccasmmg when you are available re do you know why `reset()`  might not be working for the SimpleEditor?

2024-01-03 10:47 UTC, luccasmmg commented
> @luccasmmg when you are available re do you know why `reset()` might not be working for the SimpleEditor?

The simpleeditor is a controlled component, meaning that the state is kept inside the component itself, https://react-hook-form.com/get-started#IntegratingControlledInputs i THINK it might work if you do this 

"For controlled components you will need to pass defaultValues to useForm in order to reset the Controller components' value."

So i think if you do `formObj.reset({description: ''})` it might work

2024-01-04 19:41 UTC, demenech requested changes
Overall it's working fine, just a few comments:

1) When rejecting and providing feedback, maybe the textarea should already be RTE
2) When adding a comment, if you add a link to a word and then click to open the context menu for the link, it's going to show up on a weird location
3) After rejecting I feel like the Approve/Reject buttons should disappear
4) The issues list should be a scrollable area with fixed height, to handle large quantities of issues

Just

2024-01-04 19:41 UTC, demenech commented on deployment/frontend/src/server/api/routers/dataset.ts
> +    CloseOpenIssue: protectedProcedure
typo here in the name of the function (initial letter is uppercase)

2024-01-05 11:19 UTC, steveoni commented
> Overall it's working fine, just a few comments:
> 
> 1. When rejecting and providing feedback, maybe the textarea should already be RTE
> 2. When adding a comment, if you add a link to a word and then click to open the context menu for the link, it's going to show up on a weird location
> 3. After rejecting I feel like the Approve/Reject buttons should disappear
> 4. The issues list should be a scrollable area with fixed height, to handle large quantities of issues
> 
> Just

@demenech I could not reproduce 2; about weird link opening. i added a link to the comment with text and I was able to click and go to the page.

>After rejecting I feel like the Approve/Reject buttons should disappear

no its not, the Reject button is not about just rejecting, is more about creating issues, and that's the only mean a user can use to create and add more issue. so till Approve is clicked all accessible user can always click reject to add more new issues

2024-01-05 16:00 UTC, demenech approved these changes
Lgtm

2024-01-05 16:00 UTC, merged