Explore Data Page design implementation
wri/wri-odp pull request #30
Opened 2023-10-16 12:21 UTC by steveoni

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: OD-134

## What is the new behavior?

- Implement Explore data page

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

![Screenshot 2023-10-16 at 13 17 47](https://github.com/wri/wri-odp/assets/20904032/8e0d42e6-96f0-46e9-820f-c196c00a76ef)

![Screenshot 2023-10-16 at 13 18 10](https://github.com/wri/wri-odp/assets/20904032/7d972b17-9a84-4350-b60f-1e4d062e7d11)
![Screenshot 2023-10-16 at 13 18 29](https://github.com/wri/wri-odp/assets/20904032/75cf0119-8dad-4346-a0e2-1f5bc210d3b6)
![Screenshot 2023-10-16 at 13 18 59](https://github.com/wri/wri-odp/assets/20904032/aed6aed7-cedb-469c-844c-720914f7df33)

2023-10-16 19:58 UTC, demenech requested changes
![image](https://github.com/wri/wri-odp/assets/16550934/82bb4b36-9129-47c3-bb5c-286482b6ec10)

1) Font weight is not right and element should be an `<a />` instead of `<span />`
2) Padding doesn't match the mock-up
3) These rows should be carousels

![image](https://github.com/wri/wri-odp/assets/16550934/561e6717-8594-49c1-8126-a79b6956992e)

5) Vertical spacing looks a bit off, in the mock-up items look closer to each other
6) Missing recently updated section

![image](https://github.com/wri/wri-odp/assets/16550934/5659de2d-11e3-4958-aa00-838c88700ea4)

7) Align to the right
8) Too close to the left


Besides that, I think the main content horizontal padding should be larger on larger screens. Note that the original mockup uses a 720p viewport.

___

## Mobile

1) I think horizontal padding should be slightly larger.
2) _Didn't find what you are looking for?_ section should be center aligned
3) Footer link groups should have wider vertical margins
4) Newsletter should be more distant from the link groups
5) WRI logo could be smaller

![image](https://github.com/wri/wri-odp/assets/16550934/c16bcb9a-974b-43f5-bf08-fcff62e9ca7a)

2023-10-16 20:00 UTC, demenech commented on deployment/frontend/tailwind.config.ts
> +        acumin: ['"Acumin Pro"', ...defaultTheme.fontFamily.sans],
Since this font is everywhere, I would put it on the the `_document.tsx` file, so that you don't have to specify it on every component

2023-10-16 20:44 UTC, steveoni commented
@demenech what do you mean in the last phrase `Font weight is not right and element should be an instead if`

2023-10-16 20:46 UTC, steveoni commented on deployment/frontend/tailwind.config.ts
> +        acumin: ['"Acumin Pro"', ...defaultTheme.fontFamily.sans],
@demenech sure, but we can't say for all pages to be implemented yet unless you've gone through all and seen that the default font we have.

2023-10-16 21:28 UTC, demenech commented on deployment/frontend/tailwind.config.ts
> +        acumin: ['"Acumin Pro"', ...defaultTheme.fontFamily.sans],
Makes sense

2023-10-16 21:29 UTC, demenech commented
> @demenech what do you mean in the last phrase `Font weight is not right and element should be an instead if`

apologies! It's fixed now

2023-10-18 00:36 UTC, demenech approved these changes
LGTM

2023-10-18 00:36 UTC, merged