Dashboard: User Authentication flow Mockup
wri/wri-odp pull request #59
Opened 2023-10-28 18:50 UTC by steveoni

## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: ODP-150

## What is the new behavior?

Mockup implementation
-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

![Screenshot 2023-10-28 at 19 43 07](https://github.com/wri/wri-odp/assets/20904032/7a526a4d-3e3d-4376-99ba-542d30faee74)
![Screenshot 2023-10-28 at 19 43 25](https://github.com/wri/wri-odp/assets/20904032/b732f2cc-ba84-42b4-a201-cac0a7344b90)
![Screenshot 2023-10-28 at 19 43 49](https://github.com/wri/wri-odp/assets/20904032/d263c223-8317-4161-ba11-b0a276950908)
![Screenshot 2023-10-28 at 19 44 09](https://github.com/wri/wri-odp/assets/20904032/aad2b042-cb8c-45e0-81e0-1bd15316b1d4)
![Screenshot 2023-10-28 at 19 44 28](https://github.com/wri/wri-odp/assets/20904032/ad23bb3d-09c4-4a3f-bd37-9044733e464b)
![Screenshot 2023-10-28 at 19 44 45](https://github.com/wri/wri-odp/assets/20904032/e1979e7c-11d1-40a6-861f-ea15de59cf6c)
![Screenshot 2023-10-28 at 19 45 10](https://github.com/wri/wri-odp/assets/20904032/433a8b09-5fab-49a6-add1-a2326081dece)
![Screenshot 2023-10-28 at 19 45 28](https://github.com/wri/wri-odp/assets/20904032/cf408269-a49f-493a-86c5-3851f69c2260)
![Screenshot 2023-10-28 at 19 45 50](https://github.com/wri/wri-odp/assets/20904032/ac823ca7-99ef-403b-90fd-b6e22aa837e1)
![Screenshot 2023-10-28 at 19 46 10](https://github.com/wri/wri-odp/assets/20904032/b8816f89-e571-43e5-82a1-0a3de722d2cf)
![Screenshot 2023-10-28 at 19 46 37](https://github.com/wri/wri-odp/assets/20904032/c5d6aa88-1c64-44cb-b252-82d1fadc17fd)

2023-10-30 14:35 UTC, luccasmmg requested changes
I think this is all, the main thing is the margin-top in the footer + the weird behaviour in the sidebar(with the scroll)

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/Layout.tsx
> +                          <li key={item.name} className={` text-center py-6 ${item.active ? "bg-white text-wri-black" : " text-white"}`}>
Im pretty sure those should do something on hover

![image](https://github.com/wri/wri-odp/assets/11317382/46467581-e550-494c-a43a-378c27a2b2af)

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/Layout.tsx
> +                              {item.count ? (<div className="text-[0.688rem] font-semibold bg-wri-gold text-black  flex justify-center items-center w-4 h-4 rounded-full ">{item.count}</div>) : ""}
The yellow circle is closer to h-5 w-5 than to h-4 and w-4 in the mockup

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/QuickAction.tsx
> +          <div className='font-normal text-base'>Add a dataset</div>
This should be bold on hover

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/Notifications.tsx
> +    <div className='flex flex-col sm:flex-row gap-x-4 hover:bg-slate-100 p-1 mb-2 pb-2 rounded-md'>
I think this should have more padding, on the mockup the distance between the circle and the border is 0.76 which rounds up to px-3 

![image](https://github.com/wri/wri-odp/assets/11317382/ac6ebf28-7fd8-4cd3-a15e-c83009c151f5)

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/Notifications.tsx
> +    <div className='flex flex-col sm:flex-row gap-x-4 hover:bg-slate-100 p-1 mb-2 pb-2 rounded-md'>
This actually needs to be changed on the favorites and activity-stream they all have roughly px-3

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/Layout.tsx
> +        {/* Static sidebar for desktop */}
The footer has a mt-16, which adds this blank space here, ideally you should remove that margin 
![image](https://github.com/wri/wri-odp/assets/11317382/df88f108-b58b-4551-a5fb-a452ca4e9256)

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/Dashboard.tsx
> +    <div className="relative max-w-8xl mx-auto w-full py-12 px-4 sm:px-6 lg:px-8">
Dont know where to comment this, but the main section background is not white, there is a difference in color, but because monika groups everything together you cant get the correct, color, you should ask her 
![image](https://github.com/wri/wri-odp/assets/11317382/22ab82a4-c440-495b-9dd1-346b8fb7b4f7)

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/Layout.tsx
> +                              <li key={item.name} className={` text-center py-6 ${item.active ? "bg-white text-wri-black" : " text-white"}`}>
I dont think the active is working correctly, there also shouldnt be a max-height to this sidebar, otherwise it adds this scrollbar 
![image](https://github.com/wri/wri-odp/assets/11317382/b859b1d5-402b-436b-ba63-b83b447a1c0d)

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/teams/TeamCard.tsx
> +                label: "View team",
This view team button should do something on hover, ideally you would use the <Button> component with the outline variant 
![image](https://github.com/wri/wri-odp/assets/11317382/d529a3a2-c1e4-48a1-a822-1f336f914530)

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/_shared/Pagination.tsx
> +    <div className='flex font-acumin gap-x-2 items-center self-end'>
This needs to have more padding, also the colors dont seem right(you cant get the correct from figma because monika added an image)

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/_shared/TableHeader.tsx
> +    <div className='flex w-full h-[72px] sm:items-center gap-y-4 flex-col sm:flex-row'>
Where did you get this height, it seems off from the mockup

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/approval/ApprovalRow.tsx
> +      linkButton={{
Same thing as before, all these buttons should ideally do something on hover

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/approval/ApprovalRow.tsx
> +      linkButton={{
also i think the colors are off
mockup
![image](https://github.com/wri/wri-odp/assets/11317382/89d0e28d-87ea-498a-9dfe-0fb5753a03b8)
implementation
![image](https://github.com/wri/wri-odp/assets/11317382/d004a9bf-6295-43a0-89a2-882b48c902d2)

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/_shared/ActivityStreamCard.tsx
>    icon: string
I think these icons need to have a rounded background with a shadow 
![Uploading image.png…]()

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/_shared/Row.tsx
> +export default function Row({ rowMain, rowSub, isDropDown, controlButtons, linkButton, groupStyle, className }: RowProps) {
You should probably use a @headless/ui Disclosure element, also add a nice transition so it appears as an animation

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/_shared/Row.tsx
> +export default function Row({ rowMain, rowSub, isDropDown, controlButtons, linkButton, groupStyle, className }: RowProps) {
also the entire element should change color after click(even if its not hovered) you can check the DataFiles.tsx component 

Or just how you did the topics dropdown

2023-10-30 14:35 UTC, luccasmmg commented on deployment/frontend/src/components/dashboard/topics/TopicCard.tsx
> +    <div className='flex py-3 pl-4 sm:pl-8'>
I think this vertical padding should be py-5(in figma its 20px roughly which is closer to py-5) also the image inside should have rounded corners

2023-11-01 11:44 UTC, steveoni commented
thanks @luccasmmg . i don't know why i didn't see the notification

2023-11-01 14:47 UTC, steveoni commented on deployment/frontend/src/components/dashboard/Layout.tsx
> +                              <li key={item.name} className={` text-center py-6 ${item.active ? "bg-white text-wri-black" : " text-white"}`}>
@luccasmmg for the active not working correctly: do you mean when in activity stream it also  makes the background for Dataset white also. 

i can't replicate that

2023-11-01 16:19 UTC, steveoni commented on deployment/frontend/src/components/dashboard/Dashboard.tsx
> +    <div className="relative max-w-8xl mx-auto w-full py-12 px-4 sm:px-6 lg:px-8">
monika said its white

2023-11-01 17:00 UTC, steveoni commented
@luccasmmg i add some update apart from the hover color for rows and pagination color, which i'm yet to have feedback from Monika. you can check if others are okay now

2023-11-02 11:24 UTC, luccasmmg approved these changes
LGTM

2023-11-02 11:34 UTC, merged